OBJECTS += \
Goop/2xsai.o \
Goop/animators.o \
Goop/base_action.o \
Goop/base_animator.o \
Goop/detect_event.o \
Goop/distortion.o \
Goop/events.o \
Goop/font.o \
Goop/game.o \
Goop/game_actions.o \
Goop/gconsole.o \
Goop/gfx.o \
Goop/glua.o \
Goop/gusanos.o \
Goop/hash_table.o \
Goop/level.o \
Goop/level_effect.o \
Goop/material.o \
Goop/menu.o \
Goop/noise_line.o \
Goop/parser.o \
Goop/resource_base.o \
Goop/resource_list.o \
Goop/script.o \
Goop/sprite.o \
Goop/sprite_set.o \
Goop/timer_event.o \
Goop/viewport.o \

include Goop/blitters/objects.make
include Goop/input/objects.make
include Goop/loaders/objects.make
include Goop/lua/objects.make
include Goop/object/objects.make
include Goop/player/objects.make
include Goop/sfx/objects.make
include Goop/worm/objects.make
