OBJECTS += \
Goop/2xsai.o \
Goop/animators.o \
Goop/base_action.o \
Goop/base_animator.o \
Goop/base_object.o \
Goop/base_player.o \
Goop/base_worm.o \
Goop/detect_event.o \
Goop/distortion.o \
Goop/events.o \
Goop/exp_type.o \
Goop/explosion.o \
Goop/font.o \
Goop/game.o \
Goop/game_actions.o \
Goop/gconsole.o \
Goop/gfx.o \
Goop/glua.o \
Goop/gusanos.o \
Goop/hash_table.o \
Goop/keyboard.o \
Goop/keys.o \
Goop/level.o \
Goop/level_effect.o \
Goop/material.o \
Goop/menu.o \
Goop/mouse.o \
Goop/ninjarope.o \
Goop/noise_line.o \
Goop/objects_list.o \
Goop/parser.o \
Goop/part_type.o \
Goop/particle.o \
Goop/player.o \
Goop/player_ai.o \
Goop/player_input.o \
Goop/player_options.o \
Goop/resource_base.o \
Goop/resource_list.o \
Goop/script.o \
Goop/sfx.o \
Goop/simple_particle.o \
Goop/sound.o \
Goop/sound1d.o \
Goop/sprite.o \
Goop/sprite_set.o \
Goop/timer_event.o \
Goop/viewport.o \
Goop/weapon.o \
Goop/weapon_type.o \
Goop/worm.o

include Goop/blitters/objects.make
include Goop/loaders/objects.make
include Goop/lua/objects.make
